workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == "dev"

stages:
  - build

build-for-debian:
  stage: build
  image: romzorus/deb-rust-build:v1.0
  script:
   - cargo build --release
   - mkdir -p building/deb/duxtool/usr/bin
   - cp target/release/all-in-one-worker building/deb/duxtool/usr/bin/duxtool
   - chmod -R 755 building/deb/duxtool
   - dpkg-deb --build building/deb/duxtool
  artifacts:
    paths:
    - building/deb/duxtool.deb

build-for-fedora:
  stage: build
  image: romzorus/rpm-rust-build:v1.0
  script:
   - cargo build --release
   - cp building/rpm/dux.spec ~/rpmbuild/SPECS
   - mkdir ~/rpmbuild/BUILDROOT/duxtool-0.0.1-0.x86_64/
   - cp target/release/all-in-one-worker ~/rpmbuild/BUILD/duxtool
   - rpmbuild -bb ~/rpmbuild/SPECS/dux.spec
   - cp ~/rpmbuild/RPMS/x86_64/*rpm .
  artifacts:
    paths:
    - "*.rpm"