workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == "main"

variables:
  DUX_VERSION: "0.0.1"

stages:
  - build
  - deploy

build-for-debian:
  stage: build
  image: romzorus/deb-rust-build:v1.0
  script:
   - cargo build --release
   - mkdir -p building/deb/duxtool/usr/bin
   - cp target/release/all-in-one-worker building/deb/duxtool/usr/bin/duxtool
   - chmod -R 755 building/deb/duxtool
   - dpkg-deb --build building/deb/duxtool
   - mv building/deb/duxtool.deb building/deb/duxtool-$DUX_VERSION.deb
  artifacts:
    paths:
    - building/deb/duxtool-$DUX_VERSION.deb

build-for-fedora:
  stage: build
  image: romzorus/rpm-rust-build:v1.0
  script:
   - cargo build --release
   - cp building/rpm/dux.spec ~/rpmbuild/SPECS
   - mkdir ~/rpmbuild/BUILDROOT/duxtool-$DUX_VERSION-0.x86_64/
   - cp target/release/all-in-one-worker ~/rpmbuild/BUILD/duxtool
   - rpmbuild -bb ~/rpmbuild/SPECS/dux.spec
   - cp ~/rpmbuild/RPMS/x86_64/*rpm .
  artifacts:
    paths:
    - "*.rpm"

upload-to-package-registry:
  stage: deploy
  script:
    - 'curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file building/deb/duxtool-$DUX_VERSION.deb "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/duxtool/$DUX_VERSION/duxtool-$DUX_VERSION.deb"'
    - 'curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file duxtool-$DUX_VERSION-0.x86_64.rpm "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/duxtool/$DUX_VERSION/duxtool-$DUX_VERSION-0.x86_64.rpm"'
