default:
 image: rust:slim-buster

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == "master"

stages:
  - build
  - test

release-building:
  stage: build
  script:
   - cargo build --release --verbose

testing:
  stage: test
  script:
   - cargo test