workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == "dev"

stages:
  - build

build-for-debian:
  stage: build
  image: romzorus/deb-rust-build:v1.0
  script:
   - cargo build --release --verbose
   - mkdir -p building/duxtool/usr/bin
   - cp target/release/all-in-one-worker building/duxtool/usr/bin/duxtool
   - chmod -R 755 building/duxtool
   - dpkg-deb --build building/duxtool
  artifacts:
    paths:
    - building/duxtool.deb