[workspace]
members = [
	"lib/taskexec",
	"lib/taskparser",
	"lib/cli",
	"all-in-one-worker",
	"lib/hostparser",
	"lib/connection",
	"lib/errors",
	"scalable-version/controller",
	"scalable-version/worker"
]
